### PR TITLE
Update of "ecosystem notebook" with zfit

### PR DESCRIPTION
**Pull request by jonas-eschle**
I've made some updates to the notebook, minor changes but small improvements.

I removed TensorFlow from the conda requirement, as we need 2.5 and there is only 2.4.1 in conda currently.

Does this work for you? Let me know in case it's not

### CODE REVIEW

**Comment by eduardo-rodrigues** [comment]
Hi @mayou36, many thanks for looking into the notebook. Should I then close https://github.com/eduardo-rodrigues/2021-06-14_ESCAPESummerSchool/pull/4 and go with this only? Fine by me.

Thank you!

**Comment by jonas-eschle** [comment]
Feel free to just merge it into yours and continue on #4

**Comment by eduardo-rodrigues** [comment]
> Feel free to just merge it into yours and continue on #4

Then I will merge my PR and will update with this one. That involves no manipulations. Thanks again.

**Comment by jonas-eschle** [comment]
Sure? I made this PR against the zfit-notebook branch, but I can change the base. Can you edit my branch? Cause it's my and your repo, so not sure about the rights

**Comment by eduardo-rodrigues** [comment]
If you can quickly rebase on master and recreate a PR then we're done :-).

**Pull request closed without merging**
